"SELECT COLUMN_NAME ,
           COUNT ( * ) ,
           MAX(NUM_DISTINCT) MAX_DISTINCT , 
           LISTAGG ( TABLE_NAME || '.' ||NUM_DISTINCT , CHR(10) ) WITHIN GROUP ( ORDER BY NUM_DISTINCT DESC) TABLE_LIST
      FROM USER_TAB_COLUMNS
     WHERE DATA_TYPE <> 'DATE'
  GROUP BY COLUMN_NAME
HAVING COUNT ( * ) > 1
  ORDER BY MAX_DISTINCT DESC"