select ('CREATE OR REPLACE SYNONYM ' || table_name || ' FOR ' || owner || '.' || table_name || ';')
from all_tables where owner='AMPT_OWNER';




CREATE OR REPLACE SYNONYM MP_TIER FOR AMPT_OWNER.MP_TIER;
CREATE OR REPLACE SYNONYM MP_LINE_SALES_TARGET_ASSOC FOR AMPT_OWNER.MP_LINE_SALES_TARGET_ASSOC;
CREATE OR REPLACE SYNONYM MP_PROPOSAL_CAMPAIGN_OBJECTIVE FOR AMPT_OWNER.MP_PROPOSAL_CAMPAIGN_OBJECTIVE;
CREATE OR REPLACE SYNONYM MP_SALES_TARGET FOR AMPT_OWNER.MP_SALES_TARGET;
CREATE OR REPLACE SYNONYM MP_JOB_CONFIG FOR AMPT_OWNER.MP_JOB_CONFIG;
CREATE OR REPLACE SYNONYM MP_JOB_SCHEDULE FOR AMPT_OWNER.MP_JOB_SCHEDULE;
CREATE OR REPLACE SYNONYM MP_LINE_TEMP_ATTR_ASSOC FOR AMPT_OWNER.MP_LINE_TEMP_ATTR_ASSOC;
CREATE OR REPLACE SYNONYM MP_MEDIA_TEMPLATES_SHEET FOR AMPT_OWNER.MP_MEDIA_TEMPLATES_SHEET;
CREATE OR REPLACE SYNONYM MP_AUDIENCE_TARGET_TYPE FOR AMPT_OWNER.MP_AUDIENCE_TARGET_TYPE;
CREATE OR REPLACE SYNONYM MP_PROPOSAL_OPTIONS FOR AMPT_OWNER.MP_PROPOSAL_OPTIONS;
CREATE OR REPLACE SYNONYM MP_PROPOSALS FOR AMPT_OWNER.MP_PROPOSALS;
CREATE OR REPLACE SYNONYM MP_RATE_PROFILE_ASSOC FOR AMPT_OWNER.MP_RATE_PROFILE_ASSOC;
CREATE OR REPLACE SYNONYM MP_RATE_PROFILE FOR AMPT_OWNER.MP_RATE_PROFILE;
CREATE OR REPLACE SYNONYM MP_MEDIA_PLAN_ATTRIBUTES FOR AMPT_OWNER.MP_MEDIA_PLAN_ATTRIBUTES;
CREATE OR REPLACE SYNONYM MP_CREATIVE_ATTRIBUTE_ASSOC FOR AMPT_OWNER.MP_CREATIVE_ATTRIBUTE_ASSOC;
CREATE OR REPLACE SYNONYM MP_CREATIVES FOR AMPT_OWNER.MP_CREATIVES;
CREATE OR REPLACE SYNONYM MP_PRODUCT_CREATIVE_ASSOC FOR AMPT_OWNER.MP_PRODUCT_CREATIVE_ASSOC;
CREATE OR REPLACE SYNONYM MP_PROPOSALS_HEAD_ATTRIBUTES FOR AMPT_OWNER.MP_PROPOSALS_HEAD_ATTRIBUTES;
CREATE OR REPLACE SYNONYM MP_PROPOSALS_HEAD FOR AMPT_OWNER.MP_PROPOSALS_HEAD;
CREATE OR REPLACE SYNONYM MP_ROLES FOR AMPT_OWNER.MP_ROLES;
CREATE OR REPLACE SYNONYM MP_USERS FOR AMPT_OWNER.MP_USERS;
CREATE OR REPLACE SYNONYM MP_COUNTRY_REGION_MAPPING FOR AMPT_OWNER.MP_COUNTRY_REGION_MAPPING;
CREATE OR REPLACE SYNONYM MP_PROPOSAL_VERSIONS FOR AMPT_OWNER.MP_PROPOSAL_VERSIONS;
CREATE OR REPLACE SYNONYM MP_PACKAGE FOR AMPT_OWNER.MP_PACKAGE;
CREATE OR REPLACE SYNONYM MP_LINE_ITEMS FOR AMPT_OWNER.MP_LINE_ITEMS;
CREATE OR REPLACE SYNONYM MP_PROPOSAL_LINE_ITEM_MAP FOR AMPT_OWNER.MP_PROPOSAL_LINE_ITEM_MAP;
CREATE OR REPLACE SYNONYM MP_LINE_ITEM_TARGET_INFO FOR AMPT_OWNER.MP_LINE_ITEM_TARGET_INFO;
CREATE OR REPLACE SYNONYM MP_LINE_ITEMS_EXCEPTIONS FOR AMPT_OWNER.MP_LINE_ITEMS_EXCEPTIONS;
CREATE OR REPLACE SYNONYM MP_USER_ROLE_ASSOC FOR AMPT_OWNER.MP_USER_ROLE_ASSOC;
CREATE OR REPLACE SYNONYM MP_AUDIENCE_TARGET FOR AMPT_OWNER.MP_AUDIENCE_TARGET;
CREATE OR REPLACE SYNONYM MP_MEDIA_TEMPLATES FOR AMPT_OWNER.MP_MEDIA_TEMPLATES;
CREATE OR REPLACE SYNONYM MP_ROLE_AUTHORITIES_ASSOC FOR AMPT_OWNER.MP_ROLE_AUTHORITIES_ASSOC;
CREATE OR REPLACE SYNONYM MP_AUTHORITIES FOR AMPT_OWNER.MP_AUTHORITIES;
CREATE OR REPLACE SYNONYM MP_USER_SALES_CATEGORIES FOR AMPT_OWNER.MP_USER_SALES_CATEGORIES;
CREATE OR REPLACE SYNONYM MP_GRID_PREF FOR AMPT_OWNER.MP_GRID_PREF;
CREATE OR REPLACE SYNONYM MP_ATTRIBUTES FOR AMPT_OWNER.MP_ATTRIBUTES;
CREATE OR REPLACE SYNONYM MP_PRODUCT_ATTRIBUTE_ASSOC FOR AMPT_OWNER.MP_PRODUCT_ATTRIBUTE_ASSOC;
CREATE OR REPLACE SYNONYM MP_DOCUMENTS FOR AMPT_OWNER.MP_DOCUMENTS;
CREATE OR REPLACE SYNONYM MP_AUDITS FOR AMPT_OWNER.MP_AUDITS;
CREATE OR REPLACE SYNONYM MP_CAMPAIGN_OBJECTIVE FOR AMPT_OWNER.MP_CAMPAIGN_OBJECTIVE;
CREATE OR REPLACE SYNONYM MP_TIER_SECTION_ASSOC FOR AMPT_OWNER.MP_TIER_SECTION_ASSOC;
CREATE OR REPLACE SYNONYM MP_TIER_PREMIUM FOR AMPT_OWNER.MP_TIER_PREMIUM;
CREATE OR REPLACE SYNONYM MP_NOTES FOR AMPT_OWNER.MP_NOTES;
CREATE OR REPLACE SYNONYM MP_LINE_ITEMS_RESERVATION FOR AMPT_OWNER.MP_LINE_ITEMS_RESERVATION;
CREATE OR REPLACE SYNONYM MP_PRODUCT FOR AMPT_OWNER.MP_PRODUCT;